package ca.yorku.my.StudyBuddy.integration;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import com.jayway.jsonpath.JsonPath;

import ca.yorku.my.StudyBuddy.StudyBuddyApplication;

@ActiveProfiles("stub")
@SpringBootTest(classes = StudyBuddyApplication.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
public class FileUploadDownloadIntegrationTests {
    
    @Autowired
    private MockMvc mockMvc;

    @Test
    void testFileUploadAndDownload() throws Exception {
        
        MockMultipartFile dummyFile = new MockMultipartFile(
            "file",            
            "test-notes.txt",  
            "text/plain",      
            "Hello Study Buddy!".getBytes() 
        );

        // 1. Upload the file and capture the result
        MvcResult uploadResult = mockMvc.perform(
            MockMvcRequestBuilders.multipart("/api/uploads")
                .file(dummyFile)
                .header("Authorization", "Bearer user123")
        ).andExpect(MockMvcResultMatchers.status().isCreated())
         .andReturn();

        // 2. Extract the actual generated path from the JSON response
        String responseContent = uploadResult.getResponse().getContentAsString();
        String generatedStoragePath = JsonPath.read(responseContent, "$.storagePath");

        // 3. Test the Download using the exact path generated by the server
        mockMvc.perform(
            MockMvcRequestBuilders.get(generatedStoragePath)
        ).andExpect(MockMvcResultMatchers.status().isOk());
    }
}